### ISSUE TITLE
TField issues

### ISSUE THREAD

**Issue by newinnovations** [klamonte/jexer#19]
1. If a TField is active in the constructor of the window (either by being the last widget created or by explicitly activated by activate(field)) there is will some trailing irregularities (second field in the picture). 

2. If the content exceeds the space on the screen it is scrolled to the left. When deleting characters it is not scrolled to the right again. Causing only a single character to be visible.

![tfield](https://user-images.githubusercontent.com/8201694/29411098-b4389a72-8353-11e7-8326-cfa2413466b7.png)

**Comment by klamonte** [comment]
Thanks for reporting this.  I'll look into it.

**Comment by newinnovations** [comment]
Just noticed that (1) doesn't happen when the window is modal.

And a third point ;-)  3. When there is an initial string for the TField, the cursor is at the first character, while I personally would like it to be at the end.

**Comment by newinnovations** [comment]
And a fourth one. The updateAction is fired on backspace, but not on delete.

**Comment by klamonte** [comment]
Keep them coming! :)  Thanks!

**Comment by klamonte** [comment]
This should make life a bit better.  On the issues:

1. The cursor was drawing outside the window.  This is now fixed in TWidget.

2. Changed the behavior to use as much of the viewable area as possible.

3. Haven't touched it yet.  You can initially get it by doing "field.onKeypress(new TKeypress(kbHome));" but I should really just put home(), end(), and setPosition() functions in the API.

4. Should be fixed now.

I'll keep this one open and attack 3) later on.
