### ISSUE TITLE
Jexer on maven central repository?

### ISSUE THREAD

**Issue by Emaxoso** [klamonte/jexer#20]
Can you push this library to the maven central repository?
It would much easier to import this in a production project then

```
<dependency>
	<groupId>com.github.klamonte</groupId>
	<artifactId>jexer</artifactId>
	<version>0.0.6</version>
</dependency>
```

Thanks ****

**Comment by klamonte** [comment]
This is in plan for both the current 0.0.5 and all future releases.  I've got an account and open Jira ticket over there, just haven't had time in my meatspace life to go through the process of getting the upload done.

Will leave this open to track changes on the pom.xml until the automated artifact bit is working.

**Comment by colinduplantis** [comment]
I'll help out with this one, if you want.

**Comment by klamonte** [comment]
Update:

I have been coding off a private GitLab repo since shortly after Microsoft purchased GitHub.  I am now only a few weeks away from cutting the next release.  But before I switched to GitLab, I had started the process for Maven central and now have "jexer" pointing to GitHub on Sonatype with no releases yet.  So I am a bit stuck: I want to move development to GitLab, and also get it in Maven central.  I would love to see the following outcome:

1. "jexer" on Sonatype pointing to GitLab.
2. The next release made at the GitLab repo being easily available via Maven central.
3. This GitHub repo mothballed with pointers to GitLab for the future.

If point 1 above is not doable, I suppose I could live with continued development on GitLab, and periodic refreshes to GitHub solely so that releases could make their way into Maven central.  I don't like this overall though because things are more likely to get lost.  On the other hand, perhaps maintaining both repos is fine in the end, since with this next release I am going to be asking around for additional maintainer(s) -- I don't have much time these days to be a proper plugged-into-the-community OSS developer.

For those who have patiently waited through the last 1.5 years, between 0.0.5 and now we have 20% more total code, lots of bugs fixed (still some to go of course), and something a bit unique:

![sixel_many_images](https://user-images.githubusercontent.com/4357501/52969902-9a0a4580-3377-11e9-800d-9714aae4decc.png)

**Comment by klamonte** [comment]
I was just able to start a new Jexer project via NetBeans download from Maven, using:

<dependency>
	<groupId>com.gitlab.klamonte</groupId>
	<artifactId>jexer</artifactId>
	<version>0.3.0</version>
</dependency>

From here on out Jexer releases will be on Maven Central.
