### ISSUE TITLE
Uninitialized read in jexer.backend.SwingTerminal

### ISSUE THREAD

**Issue by BenBE** [klamonte/jexer#28]
While running FindBugs on the jexer code I noticed two issues where initializing a SwingTerminal backend might NPE/cause an uninitialized read of field SwingTerminal.swing. This is visible as an uninitialized read in lines 419 and 541 but is ultimately caused by not initializing the swing field if the SwingUtilities.invokeAndWait call failes (see error conditions when this happens in the JavaDoc for javax.swing.SwingUtilities.invokeAndWait.

This can be somewhat mitigated IMHO by retrying on catching an InterruptedException and forwarding a RuntimeException when catching an InvocationTargetException. Also simply printing the stacktrace is not proper error handling ;-)

**Comment by klamonte** [comment]
Thanks for reporting this.  I'll get some more defensive code around that.

Error handling in a UI library is a bit more to think about, and I should probably reason out a real strategy under a new issue.  I don't want to pull in a real logging infrastructure, or go full dependency injection either.  So far I've been lucky in that most of the time they are just implementation bugs rather than true runtime environment issues.  But Jexer is slowly making its way into something useful, so this should be tracked.  Created #32 to reason about a real error handling system.
