### ISSUE TITLE
Allow access to the underlaying Swing controls

### ISSUE THREAD

**Issue by BenBE** [klamonte/jexer#33]
It would be nice if the SwingBackend allowed access to its internal SwingTerminal for more advanced configuration. In particular it would be nice if maximizing the window backing the SwingBackend could easily be achieved.

**Comment by klamonte** [comment]
You can get the SwingTerminal via Backend.getScreen() and cast to SwingTerminal.  DemoApplication does this for example in its Swing menu.  Around line 216 it checks to see if it is running on Swing and if so it adds two menu items, up at line 144 it then casts to SwingTerminal to call setFontSize().

But that still doesn't get us all the way there.  We need SwingComponent so that one can call getFrame() for the JFrame to call its setExtendedState().  Both SwingTerminal and SwingSessionInfo have it but don't expose it.  Should be easy enough then, let's get SwingComponent exposed on both.
