### ISSUE TITLE
Some visual problems on Ubuntu

### ISSUE THREAD

**Issue by newinnovations** [klamonte/jexer#5]
Nice work. Brings back feelings from the early days. On Ubuntu I experience some visual problems.

- With swing the window content is shifted almost one line down, and a bit to the right. Obscuring the bottom line. Vertical bars contain one pixel spacing on each line.

![jexer-swing](https://cloud.githubusercontent.com/assets/8201694/24580564/592899d0-170a-11e7-9ae7-9329f376a24d.png)

- Without swing, directly in GNOME Terminal, some characters are too large (maximize, close and progress dots). Also the colors seem "washed-out" compared to swing.

![jexer-terminal](https://cloud.githubusercontent.com/assets/8201694/24580613/1b4b3284-170b-11e7-9b84-8867b46160db.png)

**Comment by klamonte** [comment]
Swing side: you can adjust the vertical spacing by changing jexer.io.SwingScreen.textAdjustY.  Try setting it to -1 in getFontDimensions(): I have to do that on Windows and OSX to match the screen I see in Debian.

GNOME terminal: jexer doesn't (can't) set the font the terminal uses, hence the glyphs look different because Ubuntu's GNOME terminal isn't using Terminus (or uni-vga).  As for colors, jexer explicitly uses DOS colors for Swing (and thus get the "not-bold yellow means brown" color) but again it cannot do this for its host terminal.  (I could in theory use RGB colors, but the terminals haven't yet settled on what that really means, and unfortunately RGB colors do not have a graceful fallback on terminals that don't support them, a true VT220 would have blinking underlined stuff everywhere).

I will see if I can programmatically figure out textAdjustX/Y better.  There may be a way to make this behave consistently across all the platforms without peeking at os.name.

**Comment by newinnovations** [comment]
- Swing: I have played around with the textAdjustY and came to the conclusion that the -1 adjustment is not OS specific, but VM specific: openjdk or oracle. Oracle requires the -1 and openjdk does not, for the bars to be continuous. However both oracle and openjdk have the problem that the entire window content is shifted south-east, obscuring the bottom (status) line.

- GNOME Terminal: The problem is indeed with the "Monospace Regular" font. Many of the monospaced fonts on Ubuntu have this problem. However, I found the "Liberation Mono" font a beautiful alternative that works well with Jexer.

I would vote for an option to enable RGB colors, as the current terminal colors don't really combine that well.

**Comment by klamonte** [comment]
Took a swag at RGB colors.  How does that look in gnome-terminal?

**Comment by newinnovations** [comment]
- Much better
![jexer-rgb](https://cloud.githubusercontent.com/assets/8201694/24670334/ea6789aa-196d-11e7-8a8c-ed8e09b1ca09.png)

- There is however an issue with the mouse hovering over shadow.
![jexer-mouse2](https://cloud.githubusercontent.com/assets/8201694/24670366/0236e8c8-196e-11e7-9217-524360bdf7cd.png)

**Comment by klamonte** [comment]
I was able to see the mouse hover issue in xterm and this fixes it for me.  Does it work for you too?

**Comment by newinnovations** [comment]
- Shadow problem solved on gnome terminal as well. Nice!
- textAdjustY measurement/patch for Swing also works in Ubuntu. For the fall-back scenario I would propose to check for VM "brand" instead of OS.
- In Swing the screen is still shifted, with the bottom line falling off the window.
- In the treeview demo, I noticed that when enlarging the window the vertical scrollbar notch disappears even though the window content is "scrolled down". 
![notch](https://cloud.githubusercontent.com/assets/8201694/24828063/cd615404-1c55-11e7-8504-12ed9248a4dc.png)

**Comment by klamonte** [comment]
#17 opened to track the last noted issue.  Closing this one...
