### ISSUE TITLE
TTable component

### ISSUE THREAD

**Issue by jfcbxp** [klamonte/jexer#6]
Great work with the API! I have a question, Any forecast for the development of the TTable component? The TList component is a little hard to work with as a table

**Comment by klamonte** [comment]
No idea yet, sorry.  Trying to get qodem out the door this month, then I can pick up Jexer and Jermit heading into autumn.  I will keep TTable in mind though.

**Comment by nikiroo** [comment]
Hello,

Since I actually need something similar and am working on it "locally", are you interested?
https://github.com/nikiroo/jexer/commits/ttable

It is not complete yet (at the time of writing this comment, there is one commit in the branch): it can display tabular data, but can only select a whole line at a time -- which is actually what I need, but your mileage may vary...

I will probably update it in not too long, though.
If you have specific requirements, feel free to share them.

Regards,
Niki

**Comment by klamonte** [comment]
@nikiroo If you are willing, I am ready to incorporate your TTable code and demo into Jexer.  I am OK with doing the work of bringing the files from your branch over, but will need you to put a copyright header on every one of the files.  I would prefer the same MIT license as used elsewhere in Jexer (but with you as author) if that would be acceptable;  if that doesn't work it could be any license that is compatible with both MIT and GPLv3+.

**Comment by nikiroo** [comment]
@klamonte

Sorry for the late reply, I'm quite busy IRL for the moment.
I don't have any problem with the MIT license.

Just to make sure, the current status is good enough for you to start pulling?
If so, I'll take the branch and add a MIT snippet on each new file.

If not, I'll try to find some time to dedicate to that code base.

**Comment by klamonte** [comment]
No problem, take your time. :)  I've been busy a lot IRL too.

I haven't tested the code much, but so long as it compiles I am good with taking it as it is now.

**Comment by nikiroo** [comment]
Ok, I checked it during the week (I commute by train).
Was not good, is better now :)
I added a MIT license thingy on top of each new file.

It works, should be enough for my use case, but has currently 2 notices:
- the widget renderer has strange issues with "out of window" drawing
- the table only display tabular data, you can only select a full line at a time (which is my use case)

I intend to check if I can later improve it, but it seems good enough for me now.

BTW, I made a new pull request with 4 commits (since I slightly modify some of your code, I preferred to separate the commit).
You could technically just import the first two commits and it will still work (but now widget renderer).

Feel free to ask me if something in unclear :)

PULL REQUEST is visible here : https://github.com/klamonte/jexer/pull/38

**Comment by klamonte** [comment]
Hi @nikiroo,

Thank you for getting that together.  I wasn't able to really look at it in depth until the license was explicitly set, but got a chance to over the weekend.

I like the interaction, particularly the scrollable table and highlightable rows/columns of TBrowsableWidget.  And actually I like it so much that I felt it should really be an editable table that could lead to a Lotus 1-2-3 clone.  :)  This led to a different design built around TFields rather than TableModel, and deeper integration with the rest of Jexer via a new Table menu with operations to modify it on-the-fly, and minor changes to TField that will probably also lead to right/center/left justify later on.  A lot of TBrowsableWidget's onKeypress() / onMouseDown() will end up in TTableWidget.

I am stubbing that in now over at:  https://gitlab.com/klamonte/jexer/blob/master/src/jexer/TTableWidget.java , and would like to give you credit for the inspiration in the source and on the just-now-started Wiki: https://gitlab.com/klamonte/jexer/wikis/Wiki-TODO-List .  It will probably be a couple months before it is all there (getting busy at work again), but it is beginning.

I will continue tracking TTable over there:  https://gitlab.com/klamonte/jexer/issues/39

Thank you again for sharing your code!

**Comment by nikiroo** [comment]
You're welcome :)

Well, I'll try and have a look at the new code at some point.
I will probably need an account at GitLab, but that's OK.
(I'm not a fan of the new owner here at GitHub either, TBH.)

I'm also running into some difficulties with a few components in the library, I'll see if the new code offer a way out of them (or if not, I guess I'll open a CR).

For the current pull-request https://gitlab.com/klamonte/jexer/issues/39, note that I send some fixes once in a while (for now, just one commit, which fixes errors that are somewhat obvious once you actually try to use the thing -- it seems it was a rushed edit :( )

Regards,
Niki

**Comment by klamonte** [comment]
Closing this one, TTable will be tracked over there: https://gitlab.com/klamonte/jexer/issues/39

All issues are now to be tracked on GitLab.
